- name: Setup Nginx with Custom file
  hosts: linux2
  become: yes

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Copy file with owner and permissions
      copy:
        src: index.html
        dest: /var/www/html

    - name: Restart Nginx Service
      service:
        name: nginx
        state: started

    - name: Enable Service
      systemd_service:
        name: nginx
        enabled: true
