- name: show secrets
  hosts: linux2
  become: yes

  vars_files:
    - secret.yml

  tasks:
    - name: show password
      debug:
        msg: "My password is {{ password }}"
      no_log: true

    - name: Show API key
      debug:
        msg: "My API Key is {{ api_key }}"
      no_log: true
