- name: Install Packages
  hosts: linux2
  become: yes

  vars:
    packages_to_install:
      - tree
      - zip
      - unzip
      - jq
      - wget
      - apache2

  tasks:
    - name: Install Packages
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ packages_to_install }}"
      when: ansible_facts["distribution"] == "ubuntu"

    - name: Show Message
      debug:
        msg: "Installing {{ item }}"
      loop: "{{ packages_to_install }}"
      when: ansible_facts["distribution"] == "ubuntu"
